;;; -*- Mode: Common-Lisp; Author: denes.cselovszky@gmail.com -*-

(in-package #:sig)


;(FLI::DEFINE-PRECOMPILED-FOREIGN-OBJECT-TESTER-FUNCTIONS ((COM::PVOID) ((:POINTER COM:I-DISPATCH))))
(FLI::DEFINE-PRECOMPILED-FOREIGN-OBJECT-TESTER-FUNCTIONS ((COM::PVOID)))
